environment:
  COVERALLS_REPO_TOKEN:
    secure: 9HyE2QXavjNat9T8IeyUQKEwOwoq2hX0TILbQAme5IkP8xTvb6EzocrvikAjWUgE
  matrix:
  - nodejs_version: 'Stable'
  - nodejs_version: 14.0.0

init:
  git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test:nyc
after_test:
  - node ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info

build: off
clone_depth: 1

matrix:
 fast_finish: true
